# Generated by Django 3.0.6 on 2020-06-07 07:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_image_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='URL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=960, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='sitename',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='technology',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
