# Generated by Django 3.0.6 on 2020-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200607_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
