# Generated by Django 3.0.6 on 2020-06-07 12:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_image_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
